### ISSUE TITLE
Upgrade to dotnetcore 2.1

### ISSUE THREAD

**Issue by ryan2clw** [fiodarsazanavets/net-core-audio-demo#1]
I had to change the syntax around a little for .NET Core 2.1, plus invoked the callback after the audio file played.  I could do a pull request if you're interested.  Thank you for making this.

**Comment by fiodarsazanavets** [comment]
I have now created a library that can play audio on .NET Core in a platform-independent manner without any Node.js dependencies or even ASP.NET Core dependencies. It's available [here](https://github.com/mobiletechtracker/NetCoreAudio).

For this one, have updated .NET Core version to 2.1, as 2.0 is now obsolete.
